# Usar una imagen base de OpenJDK 17
FROM openjdk:17-jdk-alpine

# Copiar el archivo jar dentro del contenedor
COPY presentacion-0.0.1-SNAPSHOT.jar app.jar

# Exponer el puerto en el contenedor
EXPOSE 8080

# Comando para ejecutar la app
CMD ["java", "-jar", "app.jar"]
